version: '3.8'

services:

  backend:
    build: ./api
    ports:
      - "8000:8000"
    command: uvicorn main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend